export const GET_DEFECT_STATUS = "GET_DEFECT_STATUS";
export const NEW_DEFECT_STATUS = "NEW_DEFECT_STATUS";
export const UPDATE_DEFECT_STATUS ="UPDATE_DEFECT_STATUS";
export const DELETE_DEFECT_STATUS ="DELETE_DEFECT_STATUS";
export const SHOW_MODAL_DEFECT_STATUS = "SHOW_MODAL_DEFECT_STATUS";


export const GET_DEFECT_TYPES = "GET_DEFECT_TYPES";
export const NEW_DEFECT_TYPES = "NEW_DEFECT_TYPES";
export const UPDATE_DEFECT_TYPES ="UPDATE_DEFECT_TYPES";
export const DELETE_DEFECT_TYPES ="DELETE_DEFECT_TYPES";
export const SHOW_MODAL_DEFECT_TYPES = "SHOW_MODAL_DEFECT_TYPES";

export const GET_PERIORITY = "GET_PERIORITY";
export const NEW_PERIORITY = "NEW_PERIORITY";
export const UPDATE_PERIORITY ="UPDATE_PERIORITY";
export const DELETE_PERIORITY ="DELETE_PERIORITY";
export const SHOW_MODAL_PERIORITY = "SHOW_MODAL_PERIORITY";


export const GET_SEVERITY = "GET_SEVERITY";
export const NEW_SEVERITY= "NEW_SEVERITY";
export const UPDATE_SEVERITY="UPDATE_SEVERITY";
export const DELETE_SEVERITY ="DELETE_SEVERITY";
export const SHOW_MODAL_SEVERITY = "SHOW_MODAL_SEVERITY";


export const GET_RELEASES = "GET_RELEASES";
export const NEW_RELEASES = "NEW_RELEASES ";
export const UPDATE_RELEASES ="UPDATE_RELEASES ";
export const DELETE_RELEASES  ="DELETE_RELEASES ";
export const SHOW_MODAL_RELEASES  = "SHOW_MODAL_RELEASES ";

export const GET_PROJECT = "GET_PROJECT";
export const POST_PROJECT = "POST_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const GET_MODULE = "GET_MODULE";

export const GET_SUBMODULE = "GET_SUBMODULE";

export const GET_TESTS = "GET_TESTS";
export const NEW_TEST = "NEW_TEST";
export const EDIT_TEST = "EDIT_TEST";

export const SHOW_MODAL_TEST = "SHOW_MODAL_TEST";
